[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.162.1"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

# Netlify levert ook deploy previews voor pull requests
[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
